sudo: required
services:
   - docker

before_install:
   - docker build -t varadha-vinod/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run varadha-vinod/react-test npm test -- --coverage


after_success:

  - docker build -t varadha-vinod/multi-client ./client

  - docker build -t varadha-vinod/multi-nginx ./nginx

  - docker build -t varadha-vinod/multi-server ./server

  - docker build -t varadha-vinod/multi-worker ./worker


    # Log in to the docker CLI

   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
   
   - docker push varadha-vinod/multi-client
   - docker push varadha-vinod/multi-nginx
   - docker push varadha-vinod/multi-server
   - docker push varadha-vinod/multi-worker



