sudo: required
services:
   - docker

before_install:
   - docker build -t varadha-vinod/react-test -f ./client/Dockerfile.dev ./client
   
install:
          - sudo apt-get update
          - sudo apt-get install apt-transport-https ca-certificates
          - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
          - echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee /etc/apt/sources.list.d/docker.list
          - sudo apt-get update
          - sudo apt-get install docker-engine
          - sudo docker pull ubuntu

script:
  - docker run varadha-vinod/react-test npm test -- --coverage


after_success:

  - docker build -t varadha-vinod/multi-client ./client

  - docker build -t varadha-vinod/multi-nginx ./nginx

  - docker build -t varadha-vinod/multi-server ./server

  - docker build -t varadha-vinod/multi-worker ./worker


    # Log in to the docker CLI

   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
   
   - docker push varadha-vinod/multi-client
   - docker push varadha-vinod/multi-nginx
   - docker push varadha-vinod/multi-server
   - docker push varadha-vinod/multi-worker



